---
version: '3.4'

services:
  airflow:
    tty: true
    image: lynx-airflow:latest
    container_name: airflow
    environment:
      USER_ID: '${LOCAL_USER_ID:-9009}'
    volumes:
      - /dags:/home/user/airflow/dags
      - /logs:/home/user/logs
    ports:
      - '8080:8080' # Airflow webserver
      - '9001:9001' # Supervisord web interface
